### ISSUE TITLE
cifsd: unable to write and restart issue

### ISSUE THREAD

**Issue by ghost** [Andy2244/openwrt-extra#15] opened 2019-07-12 19:27 UTC
Two minor issues so far:
Received a permission error when trying to write to the share.

Restarting the daemon via `/etc/init.d/cifsd restart` or LuCI throws the following errors:
```
Sat Jul 13 02:45:21 2019 daemon.err rmmod: unloading the module failed
Sat Jul 13 02:45:21 2019 user.notice cifsd: Starting CIFS/SMB userspace service.
Sat Jul 13 02:45:21 2019 kern.err kernel: [   87.096677] kcifsd: handle_startup_event:343: Reconnect to a new user space daemon
Sat Jul 13 02:45:21 2019 kern.err kernel: [   87.104425] kcifsd: create_socket:410: Failed to bind socket: -98
Sat Jul 13 02:45:21 2019 kern.err kernel: [   87.110572] kcifsd: tcp_destroy_socket:368: Failed to shutdown socket: -107
Sat Jul 13 02:45:21 2019 kern.err kernel: [   87.117594] Failed to init TCP subsystem: -98
Sat Jul 13 02:45:21 2019 kern.err kernel: [   87.122074] kcifsd: stop_sessions:374: Stop session handler kcifsd:58026/4357
```

**Comment by Andy2244** [comment] 2019-07-12 19:42
I also get the write error, i must admit i only did a read test after the last git update. Seems something broke in the last version. Will report this upstream...

The restart errors are kinda normal, since it takes 8 seconds to kill the open smb connections and allow a module reset. I would have to stall the luci interface otherwise, so just stop wait 8 seconds and start for now. Need to think of a better way to handle restart.

**Comment by Andy2244** [comment] 2019-07-15 10:50
The write issue is fixed and i could reproduce the restart fail, discussing the issue with upstream atm.

**Comment by Andy2244** [comment] 2019-07-21 16:04
should be fixed with master

**Closed as completed by Andy2244** 2019-07-21 16:04 UTC
Labels: bug
